### ISSUE TITLE
Will this work for OpenLDAP in a normal use case?

### ISSUE THREAD

**Issue by astateofmind01** [cbueche/openldap-passthru#5]
I have an OpenLDAP server and I have an application that needs that OID (grafana),

Will this help?

Thanks.

**Comment by cbueche** [comment]
I don't understand your question. If you only want to authenticate Grafana users against LDAP, please see the [Grafana documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/).
